In [21]:
myPortfolio = [186,187,188, 15077]

# port186 = Portfolio(186)
# # port186.get_all_days()
# dt186 = port186.df

# port187 = Portfolio(187)
# # port187.get_all_days()
# dt187 = port187.df

# port188 = Portfolio(188)
# # port188.get_all_days()
# dt188 = port188.df

In [22]:
import requests
from requests.structures import CaseInsensitiveDict
import numpy_financial as npf
import numpy as np
from datetime import datetime as dt
import pandas as pd

headers = CaseInsensitiveDict()
headers["accept"] = "application/json"

In [23]:
pd.options.display.float_format = '{:.0f}'.format

In [24]:
# Objeto portafolio, donde tendrá los datos base del mismo y los datos financieros principales 
# De momento no está en uso

class Portfolio:
    __baseUrlApi = "https://fintual.cl/api/real_assets/"

    def __init__(self, id):
        urlAssetInfo         = f"{self.__baseUrlApi}{id}"
        assetInfo            = requests.get(urlAssetInfo,  headers=headers).json()['data']['attributes']
        
        self.id          = id
        self.name        = assetInfo['name']
        self.startDate   = assetInfo['start_date']
        self.lastDate    = assetInfo['last_day']['date']
        self.lastPrice   = assetInfo['last_day']["net_asset_value"]
        # self.df          = pd.DataFrame() 
        self.df          = self.get_all_days()

In [25]:
__baseUrlApi = "https://fintual.cl/api/real_assets/"
id = 186
urlAssetInfo         = f"{__baseUrlApi}{id}"
# Obtener los datos base del portafolio
assetInfo            = requests.get(urlAssetInfo,  headers=headers).json()['data']['attributes']
assetInfo

{'name': 'Risky Norris',
 'symbol': 'FM-FIN-RCN-A',
 'serie': 'A',
 'start_date': '2018-02-13',
 'end_date': None,
 'previous_asset_id': None,
 'last_day': {'net_asset_value': 3083.2207, 'date': '2024-12-25'},
 'conceptual_asset_id': 36}

In [26]:
# Url de la api de funtual necesario para obtener todos los valores existentes en el tiempo
urlAssetInfoDays  = f"{__baseUrlApi}{id}/days" #?to_date=2024-08-28

# obtenemos los datos de la api y lo pasamos a un DataFrame
assetInfoDays        = requests.get(urlAssetInfoDays,  headers=headers).json()['data']
df = pd.DataFrame(assetInfoDays)

# Nomalizamos los datos a Json
df = pd.json_normalize(df['attributes'])[['date', 'price', 'shareholders', 'total_assets', 'total_net_assets', 'outstanding_shares']]
# En caso que los datos del primer día aún no estén disponibles dejamos dicha fila fuera del DataFrame
# if pd.Series(np.isnan(df.tail(1)['total_assets']) == True).all():
#     df = df[1:-1]

# Elimina las filas las cuales no dispongan del datos clave 'total_assets'
df.dropna(subset=['total_assets'], inplace=True)

# Se cambia el formato de la columna fecha para generar filtros y crear nuevas columnas con los años, mese y día
df['date']  = pd.to_datetime(df['date'])
df['year']  = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day']   = df['date'].dt.day

In [27]:
df

,date,price,shareholders,total_assets,total_net_assets,outstanding_shares,year,month,day
2,2024-12-23,3060,56752,405994225456,296523563553,96902289,2024,12,23
3,2024-12-22,3030,56670,405604198416,292788493707,96632417,2024,12,22
4,2024-12-21,3030,56670,405603954525,292797835154,96632417,2024,12,21
5,2024-12-20,3030,56670,405603710633,292807176903,96632417,2024,12,20
6,2024-12-19,3014,56628,397444555975,290653605257,96449031,2024,12,19
...,...,...,...,...,...,...,...,...,...
2503,2018-02-17,1016,2,1133361,1133247,1115,2018,2,17
2504,2018-02-16,1016,2,1133340,1133263,1115,2018,2,16
2505,2018-02-15,1016,2,1133173,1133133,1115,2018,2,15
2506,2018-02-14,1013,2,1291954,985305,972,2018,2,14
2507,2018-02-13,1004,1,708357,401533,400,2018,2,13

In [28]:

# if pd.Series(np.isnan(df.tail(1)['total_assets']) == True).all():
#     df = df[1:-1]
    
# last_date = df.tail(1)['date']

# Cambio de nombre de las columas 
df.columns = ('fecha','precio','accionistas','activos_totales','activos_neto_totales','acciones_en_circulación', 'año', 'mes', 'día')

In [29]:
df = df[::-1].reset_index(drop=True)
df

,fecha,precio,accionistas,activos_totales,activos_neto_totales,acciones_en_circulación,año,mes,día
0,2018-02-13,1004,1,708357,401533,400,2018,2,13
1,2018-02-14,1013,2,1291954,985305,972,2018,2,14
2,2018-02-15,1016,2,1133173,1133133,1115,2018,2,15
3,2018-02-16,1016,2,1133340,1133263,1115,2018,2,16
4,2018-02-17,1016,2,1133361,1133247,1115,2018,2,17
...,...,...,...,...,...,...,...,...,...
2501,2024-12-19,3014,56628,397444555975,290653605257,96449031,2024,12,19
2502,2024-12-20,3030,56670,405603710633,292807176903,96632417,2024,12,20
2503,2024-12-21,3030,56670,405603954525,292797835154,96632417,2024,12,21
2504,2024-12-22,3030,56670,405604198416,292788493707,96632417,2024,12,22
2505,2024-12-23,3060,56752,405994225456,296523563553,96902289,2024,12,23

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2506 entries, 0 to 2505
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   fecha                    2506 non-null   datetime64[ns]
 1   precio                   2506 non-null   float64
 2   accionistas              2506 non-null   float64
 3   activos_totales          2506 non-null   float64
 4   activos_neto_totales     2506 non-null   float64
 5   acciones_en_circulación  2506 non-null   float64
 6   año                      2506 non-null   int32
 7   mes                      2506 non-null   int32
 8   día                      2506 non-null   int32
dtypes: datetime64[ns](1), float64(5), int32(3)
memory usage: 147.0 KB

In [31]:
# Obtener los valores entre dos fechas
mask = df[(df['fecha'] > '2021-02-16') & (df['fecha'] <= '2022-03-26')]
mask

,fecha,precio,accionistas,activos_totales,activos_neto_totales,acciones_en_circulación,año,mes,día
1100,2021-02-17,1961,27432,115500425689,95466355248,48677338,2021,2,17
1101,2021-02-18,1919,27491,111169150640,93729253875,48847077,2021,2,18
1102,2021-02-19,1919,27602,111646351947,93950379891,48968560,2021,2,19
1103,2021-02-20,1919,27602,111646503978,93947445993,48968560,2021,2,20
1104,2021-02-21,1918,27602,111646503978,93944383049,48968560,2021,2,21
...,...,...,...,...,...,...,...,...,...
1498,2022-03-22,1964,62431,273619208402,225771317017,114951152,2022,3,22
1499,2022-03-23,1936,62458,272004269089,222836563443,115092403,2022,3,23
1500,2022-03-24,1965,62470,275914582088,226110675868,115084196,2022,3,24
1501,2022-03-25,1953,62476,268701750344,224550123214,114989003,2022,3,25
1502,2022-03-26,1953,62476,268701750344,224542802265,114989003,2022,3,26

In [63]:
# Dado dos fechas obtener el irr a partir del precio de dicho día
sec = df[(df['fecha']>= '2023-12-23') & (df['fecha']<= '2024-12-22')]
first = sec[sec['fecha'] == '2023-12-23']
last  = sec[sec['fecha'] == '2024-12-22']
f1 = first.iloc[-1]['precio']*-1
l1 = last.iloc[-1]['precio']

# first = df[df['fecha'] == '2023-12-23']
# last  = df[df['fecha'] == '2024-12-22']
# f1 = first.iloc[-1]['precio']*-1
# l1 = last.iloc[-1]['precio']

print(f1)
print(l1)
print()
print(sec.describe()['precio'])
print()
npf.irr([f1,l1])*100

-2264.1811
3029.92

count    366
mean    2648
min     2211
25%     2537
50%     2641
75%     2738
max     3122
std      191
Name: precio, dtype: float64

33.819684299988204

In [33]:
def get_first_last_price_from_df(info):
    fi = info.iloc[0 ]['precio']
    la = info.iloc[-1]['precio']
    return fi, la


def tir_two_dates(price1, price2, to_percent = True, rou = 2):
    tir = npf.irr([price1*-1, price2])
    if to_percent == True:
        tir = tir * 100
    tir = round(tir, rou)
    return tir

In [60]:
d1 = df.iloc[0 ]['año']
d2 = df.iloc[-1]['año']

anual_info = dict()

for year in range(d1, d2+1):
    di = dict()
    info = df[df['año'] == year]

    pi , pf = get_first_last_price_from_df(info)
    di['tir'] = tir_two_dates(pi,pf)

    for x , i in info['precio'].describe().items():
        di[x] = i

    m1 = info.iloc[0 ]['mes']
    m2 = info.iloc[-1]['mes']
    
    month_info = dict()
    for month in range(m1, m2+1):
        mo = dict()
        minfo = info[info['mes'] == month]
        # print(minfo)

        mi , mf = get_first_last_price_from_df(minfo)
        mo['tir'] = tir_two_dates(mi,mf)

        # for y , j in minfo['precio'].describe().items():
        #     mo[y] = j
        # month_info[month] = mo

        month_info[month] = minfo['precio'].describe()
    
    di['months'] = month_info

    anual_info[year] = di

# anual_info[2018]['months'][2]['25%']
anual_info

{2018: {'tir': 4.15,
  'count': 322.0,
  'mean': 1091.6362804347825,
  'std': 65.48643250679008,
  'min': 973.6904,
  '25%': 1035.56225,
  '50%': 1097.50065,
  '75%': 1138.33695,
  'max': 1226.69,
  'months': {2: count     16
   mean    1013
   std        5
   min     1004
   25%     1009
   50%     1015
   75%     1016
   max     1024
   Name: precio, dtype: float64,
   3: count     31
   mean    1019
   std       22
   min      983
   25%      999
   50%     1022
   75%     1038
   max     1049
   Name: precio, dtype: float64,
   4: count     30
   mean     993
   std        8
   min      974
   25%      990
   50%      993
   75%     1000
   max     1006
   Name: precio, dtype: float64,
   5: count     31
   mean    1052
   std       18
   min     1006
   25%     1047
   50%     1058
   75%     1064
   max     1073
   Name: precio, dtype: float64,
   6: count     30
   mean    1092
   std        9
   min     1075
   25%     1086
   50%     1094
   75%     1099
   max     1104
   Name: precio, dtype: float64,
   7: count     31
   mean    1123
   std       14
   min     1099
   25%     1115
   50%     1123
   75%     1136
   max     1146
   Name: precio, dtype: float64,
   8: count     31
   mean    1155
   std       23
   min     1110
   25%     1136
   50%     1160
   75%     1168
   max     1207
   Name: precio, dtype: float64,
   9: count     30
   mean    1200
   std       17
   min     1168
   25%     1185
   50%     1207
   75%     1210
   max     1227
   Name: precio, dtype: float64,
   10: count     31
   mean    1144
   std       25
   min     1100
   25%     1132
   50%     1138
   75%     1166
   max     1192
   Name: precio, dtype: float64,
   11: count     30
   mean    1118
   std       27
   min     1074
   25%     1097
   50%     1121
   75%     1145
   max     1152
   Name: precio, dtype: float64,
   12: count     31
   mean    1063
   std       38
   min      986
   25%     1045
   50%     1075
   75%     1090
   max     1127
   Name: precio, dtype: float64}},
 2019: {'tir': 37.52,
  'count': 365.0,
  'mean': 1235.4114597260275,
  'std': 116.67786827002895,
  'min': 1035.5381,
  '25%': 1158.9678,
  '50%': 1218.927,
  '75%': 1285.2729,
  'max': 1551.9624,
  'months': {1: count     31
   mean    1068
   std       13
   min     1036
   25%     1061
   50%     1067
   75%     1078
   max     1089
   Name: precio, dtype: float64,
   2: count     28
   mean    1097
   std       14
   min     1076
   25%     1081
   50%     1102
   75%     1105
   max     1117
   Name: precio, dtype: float64,
   3: count     31
   mean    1136
   std       18
   min     1103
   25%     1117
   50%     1141
   75%     1146
   max     1162
   Name: precio, dtype: float64,
   4: count     30
   mean    1171
   std       16
   min     1154
   25%     1161
   50%     1163
   75%     1180
   max     1206
   Name: precio, dtype: float64,
   5: count     31
   mean    1194
   std        9
   min     1176
   25%     1188
   50%     1193
   75%     1201
   max     1208
   Name: precio, dtype: float64,
   6: count     30
   mean    1201
   std       15
   min     1164
   25%     1194
   50%     1203
   75%     1214
   max     1221
   Name: precio, dtype: float64,
   7: count     31
   mean    1238
   std       16
   min     1209
   25%     1228
   50%     1233
   75%     1252
   max     1267
   Name: precio, dtype: float64,
   8: count     31
   mean    1246
   std       13
   min     1217
   25%     1235
   50%     1250
   75%     1253
   max     1269
   Name: precio, dtype: float64,
   9: count     30
   mean    1285
   std        9
   min     1268
   25%     1279
   50%     1286
   75%     1291
   max     1301
   Name: precio, dtype: float64,
   10: count     31
   mean    1291
   std       26
   min     1257
   25%     1272
   50%     1275
   75%     1311
   max     1346
   Name: precio, dtype: float64,
   11: count     30
   mean    1438
   std       58
   min     1346
   25%     1385
   50%     1454
   75%     1474
   max     1552
   Name: precio, dtype: float64,
   12: count     31
   mean    1451
   std       19
   min     1431
   25%     1440
   50%     1448
   75%     1456
   max     1518
   Name: precio, dtype: float64}},
 2020: {'tir': 23.09,
  'count': 366.0,
  'mean': 1574.0360188524594,
  'std': 140.69409277825343,
  'min': 1174.8049,
  '25%': 1476.092925,
  '50%': 1564.64275,
  '75%': 1684.756725,
  'max': 1814.1689,
  'months': {1: count     31
   mean    1509
   std       29
   min     1438
   25%     1491
   50%     1523
   75%     1528
   max     1560
   Name: precio, dtype: float64,
   2: count     29
   mean    1561
   std       50
   min     1448
   25%     1536
   50%     1565
   75%     1598
   max     1618
   Name: precio, dtype: float64,
   3: count     31
   mean    1338
   std      106
   min     1175
   25%     1263
   50%     1329
   75%     1444
   max     1518
   Name: precio, dtype: float64,
   4: count     30
   mean    1411
   std       62
   min     1288
   25%     1396
   50%     1438
   75%     1463
   max     1482
   Name: precio, dtype: float64,
   5: count     31
   mean    1464
   std       20
   min     1416
   25%     1450
   50%     1467
   75%     1477
   max     1503
   Name: precio, dtype: float64,
   6: count     30
   mean    1513
   std       38
   min     1447
   25%     1483
   50%     1506
   75%     1550
   max     1581
   Name: precio, dtype: float64,
   7: count     31
   mean    1558
   std       20
   min     1525
   25%     1545
   50%     1557
   75%     1576
   max     1596
   Name: precio, dtype: float64,
   8: count     31
   mean    1660
   std       49
   min     1543
   25%     1634
   50%     1667
   75%     1689
   max     1722
   Name: precio, dtype: float64,
   9: count     30
   mean    1633
   std       39
   min     1591
   25%     1605
   50%     1623
   75%     1653
   max     1747
   Name: precio, dtype: float64,
   10: count     31
   mean    1719
   std       55
   min     1605
   25%     1681
   50%     1719
   75%     1770
   max     1802
   Name: precio, dtype: float64,
   11: count     30
   mean    1734
   std       57
   min     1605
   25%     1705
   50%     1741
   75%     1766
   max     1811
   Name: precio, dtype: float64,
   12: count     31
   mean    1787
   std       19
   min     1759
   25%     1770
   50%     1789
   75%     1804
   max     1814
   Name: precio, dtype: float64}},
 2021: {'tir': 31.16,
  'count': 365.0,
  'mean': 2001.5151569863017,
  'std': 175.2432850313113,
  'min': 1711.6912,
  '25%': 1855.1156,
  '50%': 1980.1353,
  '75%': 2096.9327,
  'max': 2375.3247,
  'months': {1: count     31
   mean    1849
   std       54
   min     1732
   25%     1837
   50%     1869
   75%     1894
   max     1925
   Name: precio, dtype: float64,
   2: count     28
   mean    1922
   std       60
   min     1793
   25%     1881
   50%     1937
   75%     1970
   max     1991
   Name: precio, dtype: float64,
   3: count     31
   mean    1813
   std       29
   min     1759
   25%     1800
   50%     1812
   75%     1820
   max     1884
   Name: precio, dtype: float64,
   4: count     30
   mean    1848
   std       19
   min     1795
   25%     1833
   50%     1847
   75%     1856
   max     1880
   Name: precio, dtype: float64,
   5: count     31
   mean    1802
   std       53
   min     1712
   25%     1768
   50%     1790
   75%     1849
   max     1884
   Name: precio, dtype: float64,
   6: count     30
   mean    1905
   std       40
   min     1839
   25%     1867
   50%     1895
   75%     1935
   max     1990
   Name: precio, dtype: float64,
   7: count     31
   mean    1989
   std       13
   min     1956
   25%     1980
   50%     1990
   75%     2002
   max     2014
   Name: precio, dtype: float64,
   8: count     31
   mean    2061
   std       25
   min     2002
   25%     2046
   50%     2063
   75%     2080
   max     2097
   Name: precio, dtype: float64,
   9: count     30
   mean    2080
   std       21
   min     2032
   25%     2076
   50%     2079
   75%     2093
   max     2119
   Name: precio, dtype: float64,
   10: count     31
   mean    2144
   std       56
   min     2024
   25%     2108
   50%     2177
   75%     2191
   max     2213
   Name: precio, dtype: float64,
   11: count     30
   mean    2293
   std       43
   min     2211
   25%     2275
   50%     2288
   75%     2304
   max     2375
   Name: precio, dtype: float64,
   12: count     31
   mean    2307
   std       41
   min     2243
   25%     2267
   50%     2321
   75%     2339
   max     2368
   Name: precio, dtype: float64}},
 2022: {'tir': -26.48,
  'count': 365.0,
  'mean': 1915.030038630137,
  'std': 113.06507657027794,
  'min': 1680.5236,
  '25%': 1841.3884,
  '50%': 1899.688,
  '75%': 1970.6953,
  'max': 2352.455,
  'months': {1: count     31
   mean    2118
   std      134
   min     1900
   25%     1978
   50%     2154
   75%     2206
   max     2352
   Name: precio, dtype: float64,
   2: count     28
   mean    1987
   std       59
   min     1854
   25%     1945
   50%     1974
   75%     2030
   max     2108
   Name: precio, dtype: float64,
   3: count     31
   mean    1921
   std       47
   min     1824
   25%     1887
   50%     1928
   75%     1959
   max     1980
   Name: precio, dtype: float64,
   4: count     30
   mean    1918
   std       26
   min     1872
   25%     1895
   50%     1916
   75%     1940
   max     1954
   Name: precio, dtype: float64,
   5: count     31
   mean    1837
   std       56
   min     1755
   25%     1795
   50%     1836
   75%     1872
   max     1981
   Name: precio, dtype: float64,
   6: count     30
   mean    1814
   std       63
   min     1722
   25%     1760
   50%     1803
   75%     1856
   max     1925
   Name: precio, dtype: float64,
   7: count     31
   mean    1995
   std       52
   min     1893
   25%     1970
   50%     2004
   75%     2023
   max     2122
   Name: precio, dtype: float64,
   8: count     31
   mean    2020
   std       64
   min     1870
   25%     1985
   50%     2036
   75%     2050
   max     2128
   Name: precio, dtype: float64,
   9: count     30
   mean    1874
   std       32
   min     1794
   25%     1854
   50%     1883
   75%     1896
   max     1947
   Name: precio, dtype: float64,
   10: count     31
   mean    1841
   std       48
   min     1738
   25%     1811
   50%     1853
   75%     1869
   max     1926
   Name: precio, dtype: float64,
   11: count     30
   mean    1869
   std       52
   min     1755
   25%     1825
   50%     1868
   75%     1916
   max     1943
   Name: precio, dtype: float64,
   12: count     31
   mean    1787
   std       53
   min     1681
   25%     1747
   50%     1790
   75%     1815
   max     1888
   Name: precio, dtype: float64}},
 2023: {'tir': 32.61,
  'count': 365.0,
  'mean': 1943.1916317808218,
  'std': 168.96121570450381,
  'min': 1684.3173,
  '25%': 1771.2368,
  '50%': 1944.6561,
  '75%': 2088.1245,
  'max': 2301.9894,
  'months': {1: count     31
   mean    1730
   std       18
   min     1693
   25%     1715
   50%     1735
   75%     1741
   max     1757
   Name: precio, dtype: float64,
   2: count     28
   mean    1761
   std       19
   min     1722
   25%     1749
   50%     1764
   75%     1773
   max     1794
   Name: precio, dtype: float64,
   3: count     31
   mean    1751
   std       32
   min     1684
   25%     1733
   50%     1762
   75%     1774
   max     1794
   Name: precio, dtype: float64,
   4: count     30
   mean    1787
   std       17
   min     1757
   25%     1777
   50%     1783
   75%     1803
   max     1827
   Name: precio, dtype: float64,
   5: count     31
   mean    1797
   std       42
   min     1746
   25%     1764
   50%     1783
   75%     1822
   max     1863
   Name: precio, dtype: float64,
   6: count     30
   mean    1905
   std       32
   min     1855
   25%     1874
   50%     1919
   75%     1930
   max     1953
   Name: precio, dtype: float64,
   7: count     31
   mean    2015
   std       53
   min     1936
   25%     1953
   50%     2022
   75%     2055
   max     2116
   Name: precio, dtype: float64,
   8: count     31
   mean    2055
   std       33
   min     1992
   25%     2030
   50%     2057
   75%     2079
   max     2116
   Name: precio, dtype: float64,
   9: count     30
   mean    2094
   std       27
   min     2059
   25%     2068
   50%     2094
   75%     2113
   max     2137
   Name: precio, dtype: float64,
   10: count     31
   mean    2102
   std       57
   min     1988
   25%     2067
   50%     2105
   75%     2155
   max     2193
   Name: precio, dtype: float64,
   11: count     30
   mean    2107
   std       45
   min     1987
   25%     2084
   50%     2123
   75%     2131
   max     2174
   Name: precio, dtype: float64,
   12: count     31
   mean    2204
   std       62
   min     2106
   25%     2131
   50%     2213
   75%     2263
   max     2302
   Name: precio, dtype: float64}},
 2024: {'tir': 35.22,
  'count': 358.0,
  'mean': 2658.9550030726255,
  'std': 185.05228225575115,
  'min': 2210.5055,
  '25%': 2541.727375,
  '50%': 2651.3512,
  '75%': 2740.22615,
  'max': 3121.8107,
  'months': {1: count     31
   mean    2319
   std       58
   min     2211
   25%     2292
   50%     2330
   75%     2363
   max     2418
   Name: precio, dtype: float64,
   2: count     29
   mean    2545
   std       63
   min     2406
   25%     2522
   50%     2559
   75%     2594
   max     2629
   Name: precio, dtype: float64,
   3: count     31
   mean    2632
   std       55
   min     2522
   25%     2612
   50%     2635
   75%     2682
   max     2693
   Name: precio, dtype: float64,
   4: count     30
   mean    2551
   std       62
   min     2451
   25%     2515
   50%     2562
   75%     2593
   max     2694
   Name: precio, dtype: float64,
   5: count     31
   mean    2525
   std       16
   min     2492
   25%     2513
   50%     2524
   75%     2540
   max     2549
   Name: precio, dtype: float64,
   6: count     30
   mean    2652
   std       69
   min     2521
   25%     2585
   50%     2674
   75%     2707
   max     2741
   Name: precio, dtype: float64,
   7: count     31
   mean    2732
   std       28
   min     2669
   25%     2718
   50%     2728
   75%     2755
   max     2784
   Name: precio, dtype: float64,
   8: count     31
   mean    2620
   std       53
   min     2512
   25%     2577
   50%     2631
   75%     2662
   max     2704
   Name: precio, dtype: float64,
   9: count     30
   mean    2653
   std       30
   min     2584
   25%     2644
   50%     2664
   75%     2666
   max     2705
   Name: precio, dtype: float64,
   10: count     31
   mean    2797
   std       58
   min     2643
   25%     2777
   50%     2809
   75%     2838
   max     2872
   Name: precio, dtype: float64,
   11: count     30
   mean    2937
   std       51
   min     2802
   25%     2900
   50%     2955
   75%     2977
   max     3009
   Name: precio, dtype: float64,
   12: count     23
   mean    3039
   std       34
   min     2989
   25%     3016
   50%     3036
   75%     3057
   max     3122
   Name: precio, dtype: float64}}}

# Siguientes objetivos
o - Irr en el año
o - Irr entre dos fechas
o - Irr meses en el año
- Formatear números
- Crear validaciones 
- Crear clases y funciones correspondientes
- Escritura y lectura de excel con los datos, para no recurrir %100 de la API y dicho archivo poderlo usar en Excel y Power Bi
- Generación de diagramas en fechas especificas y con input
- Simular ingreseo y egreso de dinero al invertir en cierta fecha
- Forma de buscar mayor beneficio si se invirtío en cierta fecha
- Generar reportes completos